### ISSUE TITLE
PassportNFC: DEBUG: failed to get card access file: File not found

### ISSUE THREAD

**Issue by andrewkirkham** [jllarraz/AndroidPassportReader#7]
Hi,
I am getting this error when trying to scan my passport. Can you help me to figure it out what is the problem?

2019-11-25 19:44:59.511 28104-2987/? I/PassportNFC: DEBUG: failed to get card access file: File not found, CAPDU = 00A4020C02011C, RAPDU = 6A82 (SW = 0x6A82: FILE NOT FOUND)
2019-11-25 19:44:59.511 28104-2987/? W/System.err: net.sf.scuba.smartcards.CardServiceException: File not found, CAPDU = 00A4020C02011C, RAPDU = 6A82 (SW = 0x6A82: FILE NOT FOUND)
2019-11-25 19:44:59.512 28104-2987/? W/System.err:     at org.jmrtd.protocol.ReadBinaryAPDUSender.checkStatusWordAfterFileOperation(ReadBinaryAPDUSender.java:219)
2019-11-25 19:44:59.512 28104-2987/? W/System.err:     at org.jmrtd.protocol.ReadBinaryAPDUSender.sendSelectFile(ReadBinaryAPDUSender.java:80)
2019-11-25 19:44:59.512 28104-2987/? W/System.err:     at org.jmrtd.DefaultFileSystem.sendSelectFile(DefaultFileSystem.java:313)
2019-11-25 19:44:59.512 28104-2987/? W/System.err:     at org.jmrtd.DefaultFileSystem.getFileInfo(DefaultFileSystem.java:272)
2019-11-25 19:44:59.512 28104-2987/? W/System.err:     at org.jmrtd.DefaultFileSystem.getSelectedPath(DefaultFileSystem.java:129)
2019-11-25 19:44:59.512 28104-2987/? W/System.err:     at net.sf.scuba.smartcards.CardFileInputStream.<init>(CardFileInputStream.java:60)
2019-11-25 19:44:59.512 28104-2987/? W/System.err:     at org.jmrtd.PassportService.getInputStream(PassportService.java:592)
2019-11-25 19:44:59.512 28104-2987/? W/System.err:     at example.jllarraz.com.passportreader.utils.PassportNFC.<init>(PassportNFC.kt:255)
2019-11-25 19:44:59.512 28104-2987/? W/System.err:     at example.jllarraz.com.passportreader.utils.NFCDocumentTag$handleTag$1.call(NFCDocumentTag.kt:38)
2019-11-25 19:44:59.512 28104-2987/? W/System.err:     at example.jllarraz.com.passportreader.utils.NFCDocumentTag$handleTag$1.call(NFCDocumentTag.kt:23)
2019-11-25 19:44:59.512 28104-2987/? W/System.err:     at io.reactivex.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:44)
2019-11-25 19:44:59.512 28104-2987/? W/System.err:     at io.reactivex.Single.subscribe(Single.java:3603)
2019-11-25 19:44:59.512 28104-2987/? W/System.err:     at io.reactivex.internal.operators.single.SingleDoOnSubscribe.subscribeActual(SingleDoOnSubscribe.java:41)
2019-11-25 19:44:59.512 28104-2987/? W/System.err:     at io.reactivex.Single.subscribe(Single.java:3603)
2019-11-25 19:44:59.512 28104-2987/? W/System.err:     at io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
2019-11-25 19:44:59.512 28104-2987/? W/System.err:     at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)
2019-11-25 19:44:59.512 28104-2987/? W/System.err:     at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
2019-11-25 19:44:59.512 28104-2987/? W/System.err:     at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
2019-11-25 19:44:59.512 28104-2987/? W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
2019-11-25 19:44:59.512 28104-2987/? W/System.err:     at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
2019-11-25 19:44:59.512 28104-2987/? W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
2019-11-25 19:44:59.512 28104-2987/? W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
2019-11-25 19:44:59.512 28104-2987/? W/System.err:     at java.lang.Thread.run(Thread.java:764)

**Comment by andrewkirkham** [comment]
Just sorted it out by setting the nfc timeout to 10000

**Comment by zakblacki** [comment]
> Just sorted it out by setting the nfc timeout to 10000

Where is that ?

**Comment by jllarraz** [comment]
When you configure the NFC in the NFC activity

**Comment by zakblacki** [comment]
> When you configure the NFC in the NFC activity El mar., 17 dic. 2019 8:21, zakblacki <notifications@github.com> escribió:
> […](#)

Specify the line please can't find it

**Comment by sertunc** [comment]
@jllarraz I do not just copying it without understanding but I could not find nfc timeout. Can you help me again? Thank you

**Comment by jllarraz** [comment]
Hi,

You can check in the documentation
https://developer.android.com/reference/android/nfc/tech/NfcA#setTimeout(int)

So in
https://github.com/jllarraz/AndroidPassportReader/blob/master/app/src/main/java/example/jllarraz/com/passportreader/utils/NFCDocumentTag.kt
Just after

val nfc = IsoDep.get(tag)

you can set the timeout to the nfc tag.


Best regards

**Comment by naveenkrnl** [comment]
Hi I tried solving it with nfctimeout, but still the exact same errors persists. Can anyone help me out ?

Also, i am getting before this error - jank_removeInvalidNode all the node in jank list is out of time
DEBUG: failed to get card access file: File not found, CAPDU = 00A4020C020, RAPDU = 6A2 (SW = 0x682: FILE NOT FOUND) , and the rest part is same

**Comment by gruschus** [comment]
I'm getting the same issue.  I've come across that this must be used due to it contains a needed algorithm

org.spongycastle.jce.provider.BouncyCastleProvider

I still haven't got my issue resolved.

**Comment by jonneymendoza** [comment]
I tried adding a timeout of 5000 aka 5 seconds and i still get this error

**Comment by gruschus** [comment]
I use 10000 and it works for me.

**Comment by gruschus** [comment]
What is the error you are seeing?

**Comment by jonneymendoza** [comment]
The file not found

**Comment by gruschus** [comment]
If this the error you are getting
net.sf.scuba.smartcards.CardServiceException: File not found, CAPDU = 00A4020C02011D, RAPDU = 6A82 (SW = 0x6A82: FILE NOT FOUND)
        at org.jmrtd.protocol.ReadBinaryAPDUSender.checkStatusWordAfterFileOperation(ReadBinaryAPDUSender.java:218)
        at org.jmrtd.protocol.ReadBinaryAPDUSender.sendSelectFile(ReadBinaryAPDUSender.java:79)

I get it too.  I just trap the exception and continue.  It fails the PACE stuff then just goes on.

                CardService cardService = CardService.getInstance(isoDep);
                cardService.open();

                PassportService service = new PassportService(cardService, NORMAL_MAX_TRANCEIVE_LENGTH, DEFAULT_MAX_BLOCKSIZE, false, true);
                service.open();

                boolean paceSucceeded = false;
                try {
                    CardSecurityFile cardSecurityFile = new CardSecurityFile(service.getInputStream(PassportService.EF_CARD_SECURITY));
                    Collection<SecurityInfo> securityInfoCollection = cardSecurityFile.getSecurityInfos();
                    for (SecurityInfo securityInfo : securityInfoCollection) {
                        if (securityInfo instanceof PACEInfo) {
                            PACEInfo paceInfo = (PACEInfo) securityInfo;
                            service.doPACE(bacKey, paceInfo.getObjectIdentifier(), PACEInfo.toParameterSpec(paceInfo.getParameterId()), null);
                            paceSucceeded = true;
                        }
                    }
                } catch (Exception e) {
                    Log.w(TAG, e);
                }

                Log.d(TAG, "doInBackground, pace succeeded: " + paceSucceeded);

                service.sendSelectApplet(paceSucceeded);

                try {
                    if (!paceSucceeded) {
                        try {
                            service.getInputStream(PassportService.EF_COM).read();
                        } catch (Exception e) {
                            service.doBAC(bacKey);
                        }
                    }
                }
                catch (Exception e) {
                    Log.d(TAG, "doInBackground, " + e.getMessage(), e);
                    return e;
                }

                showToast("Reading information");

                // -- Personal Details -- //
                CardFileInputStream dg1In = service.getInputStream(PassportService.EF_DG1);
                DG1File dg1File = new DG1File(dg1In);

                MRZInfo mrzInfo = dg1File.getMRZInfo();
                logDebug("doInBackground, read DG1, MRZ read: " + mrzInfo.toString());

**Comment by jonneymendoza** [comment]
Ok cool I'll try that

**Comment by jonneymendoza** [comment]
May i ask what is the purpose of creating the card security file part of the code and why it fails?

**Comment by jonneymendoza** [comment]
Also, are yu able to rerieve the DG2File object? i keep getting this error below:

```
java.io.IOException: Unexpected exception
Caused by: net.sf.scuba.smartcards.CardServiceException: Read binary failed on file 102
 Caused by: net.sf.scuba.smartcards.CardServiceException: Tag was lost.
```

**Comment by jllarraz** [comment]
Not all the passports contains all the data groups. Anyway if you are having this message "Tag was lost" you can try to increase your nfc timeout and keep the passport stable during reading
